import { compile } from "json-schema-to-typescript";
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  zGetAmendment,
  zGetBill,
  zGetBillText,
  zGetMasterList,
  zGetPerson,
  zGetRollCall,
  zGetSearch,
  zGetSessionList,
  zGetSessionPeople,
  zGetSponsoredList,
  zGetSupplement,
} from "../src/schemas/types.js";

mkdirSync(resolve(import.meta.dirname, "../src/generated"), {
  recursive: true,
});

const schemas = {
  SessionList: zGetSessionList,
  Bill: zGetBill,
  MasterList: zGetMasterList,
  BillText: zGetBillText,
  Person: zGetPerson,
  Amendment: zGetAmendment,
  Supplement: zGetSupplement,
  RollCall: zGetRollCall,
  SessionPeople: zGetSessionPeople,
  SponsoredList: zGetSponsoredList,
  Search: zGetSearch,
};

let types = `/**\n * This file was automatically generated by scripts/typegen.ts. Do not edit this file directly.\n */\n\n`;
for (const [name, schema] of Object.entries(schemas)) {
  const ts = await compile(schema.toJSONSchema() as any, name, {
    bannerComment: "",
  });
  types += ts;
}

writeFileSync(resolve(import.meta.dirname, "../src/generated/types.ts"), types);
